import {
  ShieldAlert,
  TriangleAlert,
  Monitor,
  Bot,
  Target,
  Activity,
  TrendingUp,
  Gauge,
  Server,
  Database,
  AlertTriangle,
} from "lucide-react";

function StatCard({ title, value, color }) {

  const config = {
    "Total Events": {
      icon: <ShieldAlert size={24} />,
      subtitle: "Security Events"
    },
    "Critical": {
      icon: <AlertTriangle size={24} />,
      subtitle: "Immediate Action Required"
    },
    "High Severity": {
      icon: <TriangleAlert size={24} />,
      subtitle: "Needs Investigation"
    },
    "Medium": {
      icon: <Activity size={24} />,
      subtitle: "Monitor Closely"
    },
    "Low": {
      icon: <Activity size={24} />,
      subtitle: "Low Priority"
    },
    "Windows Hosts": {
      icon: <Monitor size={24} />,
      subtitle: "Protected Endpoints"
    },
    "Events / Sec": {
      icon: <Gauge size={24} />,
      subtitle: "Collector Throughput"
    },
    "Collector": {
      icon: <Server size={24} />,
      subtitle: "Collector Health"
    },
    "Database": {
      icon: <Database size={24} />,
      subtitle: "Historical Storage"
    },
    "MITRE Techniques": {
      icon: <Target size={24} />,
      subtitle: "Mapped ATT&CK"
    },
    "AI Investigations": {
      icon: <Bot size={24} />,
      subtitle: "Generated by SOCRA AI"
    }
  };

  const item = config[title] || {
    icon: <Activity size={24} />,
    subtitle: "Real-Time Metric"
  };

  return (
    <div className="group relative overflow-hidden bg-slate-900/20 border border-slate-800/80 rounded-xl p-3 transition-all duration-200">
      
      {/* Background Hover Flow Glow Effect */}
      <div
        className="absolute -top-12 -right-12 w-32 h-32 rounded-full blur-3xl opacity-0 group-hover:opacity-10 transition-opacity duration-300 pointer-events-none"
        style={{ background: color }}
      />

      {/* Header Metric Row */}
      <div className="relative flex justify-between items-center">
        <div
          className="p-1.5 rounded-lg"
          style={{
            background: `${color}15`,
            color,
          }}
        >
          {item.icon}
        </div>

        <div className="flex items-center gap-1.5 text-green-400 text-[10px] font-bold tracking-wider">
          <span className="w-1.5 h-1.5 rounded-full bg-green-400 animate-pulse" />
          <span>LIVE</span>
        </div>
      </div>

      {/* Meta Metric Label Descriptive Subtitle */}
      <p className="mt-3 text-[10px] font-bold uppercase tracking-widest text-slate-500">
        {title}
      </p>

      {/* Metric Main Dynamic Counter Section */}
      <div className="flex justify-between items-end mt-1">
        <h2
          className="text-4xl font-extrabold tracking-tight"
          style={{ color }}
        >
          {value}
        </h2>

        <div className="flex items-center gap-1 text-emerald-500 text-[10px] font-semibold pb-1">
          <TrendingUp size={12} />
          <span>Active</span>
        </div>
      </div>

      {/* Footer Text Metadata Label Area */}
      <div className="flex justify-between items-center mt-3 pt-2 border-t border-slate-900/30">
        <span className="text-[11px] font-medium text-slate-500 tracking-wide">
          {item.subtitle}
        </span>
        <span className="text-[10px] text-slate-600 font-mono">
          Real-Time
        </span>
      </div>
    </div>
  );
}

export default StatCard;