"""
SOCRA AI — Authoritative Windows Event ID Registry (SINGLE SOURCE OF TRUTH)

Event ID name/description, default severity, MITRE mapping and detection mapping
for every supported Windows / Sysmon event. Every backend module (detection
engine, severity engine, log enrichment, alerts, timeline) reads from this
registry so the same event always receives the same severity regardless of the
API path.

Generated by merging: app/rules/windows_event_rules.py (detection authority),
app/routes/logs.py registry, app/utils/enterprise_mappings.py. Conflicts resolve
in that priority order. Stored telemetry severities match this registry.
"""

import re

# Canonical severity taxonomy (highest -> lowest).
SEVERITY_ORDER = ["Critical", "High", "Medium", "Low", "Informational", "Unknown"]

SEVERITY_RANK = {"Critical": 5, "High": 4, "Medium": 3, "Low": 2, "Informational": 1, "Unknown": 0}

# ============================================================================
# DISPLAY SENTINELS (normalized enrichment)
# ----------------------------------------------------------------------------
# When an event genuinely carries no process / PID / MITRE information the
# pipeline serves these explicit values instead of fabricating data (e.g. the
# old '[System Process]' fallback for events with no process fields at all) or
# leaking ambiguous placeholders ('-', 'N/A'). Every read path (Alerts,
# Investigation, Timeline, Reports, Enterprise search) consumes the same
# sentinels so the UI never has to guess.
# ============================================================================
PROCESS_NOT_AVAILABLE = "Not available in event"
PID_NOT_AVAILABLE = "Not available"
MITRE_UNMAPPED = "Unmapped"

_EMPTY_TOKEN_VALUES = {"", "-", "None", "null", "N/A", "n/a", "(null)"}

# ============================================================================
# WINDOWS EVENT ID MASTER REGISTRY
# ============================================================================
WINDOWS_EVENT_RULES = {
    "1": {
        "cat": "General Audit",
        "description": "Sysmon recorded process creation.",
        "detection": "Sysmon Process Creation",
        "mitre": {
            "id": "T1059",
            "tactic": "Execution",
            "technique": "Command and Scripting Interpreter"
        },
        "name": "Sysmon Process Creation",
        "recommendation": "Inspect parent process and command line.",
        "severity": "Medium"
    },
    "10": {
        "cat": "General Audit",
        "description": "Process accessed another process.",
        "detection": "Process Access",
        "mitre": {
            "id": "T1003",
            "tactic": "Credential Access",
            "technique": "OS Credential Dumping"
        },
        "name": "Process Access",
        "recommendation": "Review for LSASS access.",
        "severity": "High"
    },
    "106": {
        "cat": "Task Scheduler",
        "description": "Task Scheduler Operation: Registered Task Vector Mapping.",
        "detection": "Task Scheduler Operation: Registered Task Vector Mapping",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "Task Scheduler Operation: Registered Task Vector Mapping",
        "recommendation": "Review the event manually.",
        "severity": "Low"
    },
    "11": {
        "cat": "General Audit",
        "description": "A file was created.",
        "detection": "File Created",
        "mitre": {
            "id": "T1105",
            "tactic": "Command and Control",
            "technique": "Ingress Tool Transfer"
        },
        "name": "File Created",
        "recommendation": "Inspect suspicious file paths.",
        "severity": "Low"
    },
    "1102": {
        "cat": "Defense Evasion",
        "description": "The Security Audit Log Was Cleared.",
        "detection": "The Security Audit Log Was Cleared",
        "mitre": {
            "id": "T1070.001",
            "tactic": "Defense Evasion",
            "technique": "Clear Windows Event Logs"
        },
        "name": "The Security Audit Log Was Cleared",
        "recommendation": "Review the event manually.",
        "severity": "Critical"
    },
    "1116": {
        "cat": "Antivirus",
        "description": "Windows Defender detected malware.",
        "detection": "Windows Defender Malware Detected",
        "mitre": {
            "id": "T1204",
            "tactic": "Execution",
            "technique": "User Execution"
        },
        "name": "Windows Defender: Malicious Engine Detection Alert",
        "recommendation": "Immediately isolate endpoint and investigate.",
        "severity": "Critical"
    },
    "1117": {
        "cat": "Antivirus",
        "description": "Windows Defender performed remediation.",
        "detection": "Windows Defender Remediation",
        "mitre": {
            "id": "T1562",
            "tactic": "Defense Evasion",
            "technique": "Defense Evasion"
        },
        "name": "Windows Defender: Remediated Threat Actions Succeeded",
        "recommendation": "Confirm malware removal.",
        "severity": "High"
    },
    "1118": {
        "cat": "Antivirus",
        "description": "Windows Defender: Remediation Malfunction Action Required.",
        "detection": "Windows Defender: Remediation Malfunction Action Required",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "Windows Defender: Remediation Malfunction Action Required",
        "recommendation": "Review the event manually.",
        "severity": "Critical"
    },
    "1149": {
        "cat": "RDP Terminal",
        "description": "Remote Desktop authentication succeeded.",
        "detection": "Remote Desktop Logon",
        "mitre": {
            "id": "T1021.001",
            "tactic": "Lateral Movement",
            "technique": "Remote Desktop Protocol"
        },
        "name": "RDP Network Pre-Authentication Succeeded",
        "recommendation": "Verify expected administrator activity.",
        "severity": "Medium"
    },
    "129": {
        "cat": "Task Scheduler",
        "description": "Task Scheduler Operation: Task Process Spawn Managed.",
        "detection": "Task Scheduler Operation: Task Process Spawn Managed",
        "mitre": {
            "id": "T1053.005",
            "tactic": "Persistence",
            "technique": "Scheduled Task/Job: Scheduled Task"
        },
        "name": "Task Scheduler Operation: Task Process Spawn Managed",
        "recommendation": "Review the event manually.",
        "severity": "Medium"
    },
    "13": {
        "cat": "General Audit",
        "description": "Registry value changed.",
        "detection": "Registry Value Modified",
        "mitre": {
            "id": "T1112",
            "tactic": "Defense Evasion",
            "technique": "Modify Registry"
        },
        "name": "Registry Value Modified",
        "recommendation": "Review persistence locations.",
        "severity": "Medium"
    },
    "141": {
        "cat": "Task Scheduler",
        "description": "Task Scheduler Operation: Task Action Executed Clean.",
        "detection": "Task Scheduler Operation: Task Action Executed Clean",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "Task Scheduler Operation: Task Action Executed Clean",
        "recommendation": "Review the event manually.",
        "severity": "Low"
    },
    "21": {
        "cat": "RDP Terminal",
        "description": "Terminal Services: Remote Session Ingestion Initialized.",
        "detection": "Terminal Services: Remote Session Ingestion Initialized",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "Terminal Services: Remote Session Ingestion Initialized",
        "recommendation": "Review the event manually.",
        "severity": "Medium"
    },
    "24": {
        "cat": "RDP Terminal",
        "description": "Terminal Services: Remote Session Terminated Disconnect.",
        "detection": "Terminal Services: Remote Session Terminated Disconnect",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "Terminal Services: Remote Session Terminated Disconnect",
        "recommendation": "Review the event manually.",
        "severity": "Low"
    },
    "3": {
        "cat": "General Audit",
        "description": "Network connection established.",
        "detection": "Sysmon Network Connection",
        "mitre": {
            "id": "T1071",
            "tactic": "Command and Control",
            "technique": "Application Layer Protocol"
        },
        "name": "Sysmon Network Connection",
        "recommendation": "Investigate suspicious remote IPs.",
        "severity": "Medium"
    },
    "400": {
        "cat": "PowerShell",
        "description": "PowerShell Engine Console Lifecycle Started.",
        "detection": "PowerShell Engine Console Lifecycle Started",
        "mitre": {
            "id": "T1059.001",
            "tactic": "Execution",
            "technique": "Command and Scripting Interpreter: PowerShell"
        },
        "name": "PowerShell Engine Console Lifecycle Started",
        "recommendation": "Review the event manually.",
        "severity": "Low"
    },
    "4611": {
        "cat": "System Audit",
        "description": "A Trusted Logon Process Registered with LSA.",
        "detection": "A Trusted Logon Process Registered with LSA",
        "mitre": {
            "id": "T1068",
            "tactic": "Privilege Escalation",
            "technique": "Exploitation for Privilege Escalation"
        },
        "name": "A Trusted Logon Process Registered with LSA",
        "recommendation": "Review the event manually.",
        "severity": "High"
    },
    "4616": {
        "cat": "Defense Evasion",
        "description": "The System Time Was Changed.",
        "detection": "The System Time Was Changed",
        "mitre": {
            "id": "T1070.006",
            "tactic": "Defense Evasion",
            "technique": "Indicator Removal: Timestomp"
        },
        "name": "The System Time Was Changed",
        "recommendation": "Review the event manually.",
        "severity": "Medium"
    },
    "4622": {
        "cat": "System Integrity",
        "description": "A Security Package Has Been Loaded by the LSA.",
        "detection": "A Security Package Has Been Loaded by the LSA",
        "mitre": {
            "id": "T1547.005",
            "tactic": "Unknown",
            "technique": "T1547.005"
        },
        "name": "A Security Package Has Been Loaded by the LSA",
        "recommendation": "Review the event manually.",
        "severity": "Critical"
    },
    "4624": {
        "cat": "Authentication",
        "description": "A user successfully authenticated to the system.",
        "detection": "Successful Logon",
        "mitre": {
            "id": "T1078",
            "tactic": "Defense Evasion",
            "technique": "Valid Accounts"
        },
        "name": "Successful Account Logon",
        "recommendation": "Verify login source, account and logon type.",
        "severity": "Low"
    },
    "4625": {
        "cat": "Authentication",
        "description": "Authentication failed.",
        "detection": "Failed Logon",
        "mitre": {
            "id": "T1110",
            "tactic": "Credential Access",
            "technique": "Brute Force"
        },
        "name": "Failed Account Logon",
        "recommendation": "Investigate repeated failures and possible password spraying.",
        "severity": "Medium"
    },
    "4634": {
        "cat": "Authentication",
        "description": "User logged off.",
        "detection": "User Logoff",
        "mitre": {
            "id": "N/A",
            "tactic": "N/A",
            "technique": "User Session Ended"
        },
        "name": "Account Logoff",
        "recommendation": "Normal Windows activity.",
        "severity": "Informational"
    },
    "4647": {
        "cat": "Authentication",
        "description": "User initiated logoff.",
        "detection": "User Initiated Logoff",
        "mitre": {
            "id": "N/A",
            "tactic": "N/A",
            "technique": "Interactive Logoff"
        },
        "name": "User-Initiated Logoff Sequence",
        "recommendation": "Validate session if investigation is active.",
        "severity": "Informational"
    },
    "4648": {
        "cat": "Credential Access",
        "description": "Credentials were explicitly supplied.",
        "detection": "Explicit Credential Logon",
        "mitre": {
            "id": "T1078",
            "tactic": "Defense Evasion",
            "technique": "Valid Accounts"
        },
        "name": "Logon Using Explicit Credentials",
        "recommendation": "Review source process and account usage.",
        "severity": "Medium"
    },
    "4656": {
        "cat": "Object Access",
        "description": "A Handle to an Object Was Requested (LSASS Injection).",
        "detection": "A Handle to an Object Was Requested (LSASS Injection)",
        "mitre": {
            "id": "T1003.001",
            "tactic": "Credential Access",
            "technique": "OS Credential Dumping: LSASS Memory"
        },
        "name": "A Handle to an Object Was Requested (LSASS Injection)",
        "recommendation": "Review the event manually.",
        "severity": "High"
    },
    "4657": {
        "cat": "Registry Changes",
        "description": "A Registry Value Was Modified.",
        "detection": "A Registry Value Was Modified",
        "mitre": {
            "id": "T1112",
            "tactic": "Defense Evasion",
            "technique": "Modify Registry"
        },
        "name": "A Registry Value Was Modified",
        "recommendation": "Review the event manually.",
        "severity": "Medium"
    },
    "4660": {
        "cat": "Object Access",
        "description": "An Object Was Deleted.",
        "detection": "An Object Was Deleted",
        "mitre": {
            "id": "T1070",
            "tactic": "Unknown",
            "technique": "T1070"
        },
        "name": "An Object Was Deleted",
        "recommendation": "Review the event manually.",
        "severity": "Low"
    },
    "4663": {
        "cat": "Object Access",
        "description": "Attempt Made to Access File System Object.",
        "detection": "Attempt Made to Access File System Object",
        "mitre": {
            "id": "T1222.002",
            "tactic": "Unknown",
            "technique": "T1222.002"
        },
        "name": "Attempt Made to Access File System Object",
        "recommendation": "Review the event manually.",
        "severity": "Low"
    },
    "4672": {
        "cat": "Privilege Escalation",
        "description": "Administrator-level privileges assigned.",
        "detection": "Special Privileges Assigned",
        "mitre": {
            "id": "T1068",
            "tactic": "Privilege Escalation",
            "technique": "Privilege Escalation"
        },
        "name": "Special Privileges Assigned to New Logon Token",
        "recommendation": "Verify administrative account usage.",
        "severity": "High"
    },
    "4688": {
        "cat": "Process Activity",
        "description": "A new process was created.",
        "detection": "Process Creation",
        "mitre": {
            "id": "T1059",
            "tactic": "Execution",
            "technique": "Command and Scripting Interpreter"
        },
        "name": "New Process Created",
        "recommendation": "Inspect command line and parent process.",
        "severity": "Medium"
    },
    "4689": {
        "cat": "Process Activity",
        "description": "A process terminated.",
        "detection": "Process Exit",
        "mitre": {
            "id": "N/A",
            "tactic": "N/A",
            "technique": "Process Termination"
        },
        "name": "Process Exited/Terminated",
        "recommendation": "Normal operating system activity.",
        "severity": "Informational"
    },
    "4697": {
        "cat": "Persistence",
        "description": "A new Windows service was installed.",
        "detection": "Windows Service Installed",
        "mitre": {
            "id": "T1543.003",
            "tactic": "Persistence",
            "technique": "Create or Modify System Process"
        },
        "name": "New Windows System Service Installed",
        "recommendation": "Verify service path, signer and executable.",
        "severity": "High"
    },
    "4698": {
        "cat": "Persistence",
        "description": "A scheduled task was created.",
        "detection": "Scheduled Task Created",
        "mitre": {
            "id": "T1053.005",
            "tactic": "Persistence",
            "technique": "Scheduled Task"
        },
        "name": "A Scheduled Task Was Created",
        "recommendation": "Review creator, task action and trigger.",
        "severity": "High"
    },
    "4699": {
        "cat": "Persistence",
        "description": "A Scheduled Task Was Deleted.",
        "detection": "A Scheduled Task Was Deleted",
        "mitre": {
            "id": "T1070",
            "tactic": "Unknown",
            "technique": "T1070"
        },
        "name": "A Scheduled Task Was Deleted",
        "recommendation": "Review the event manually.",
        "severity": "Low"
    },
    "4700": {
        "cat": "Persistence",
        "description": "A Scheduled Task Was Enabled.",
        "detection": "A Scheduled Task Was Enabled",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "A Scheduled Task Was Enabled",
        "recommendation": "Review the event manually.",
        "severity": "Low"
    },
    "4701": {
        "cat": "Persistence",
        "description": "A Scheduled Task Was Disabled.",
        "detection": "A Scheduled Task Was Disabled",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "A Scheduled Task Was Disabled",
        "recommendation": "Review the event manually.",
        "severity": "Low"
    },
    "4713": {
        "cat": "Policy Changes",
        "description": "Kerberos Policy Changed.",
        "detection": "Kerberos Policy Changed",
        "mitre": {
            "id": "T1556",
            "tactic": "Unknown",
            "technique": "T1556"
        },
        "name": "Kerberos Policy Changed",
        "recommendation": "Review the event manually.",
        "severity": "High"
    },
    "4719": {
        "cat": "Defense Evasion",
        "description": "Windows audit policy modified.",
        "detection": "Audit Policy Changed",
        "mitre": {
            "id": "T1562",
            "tactic": "Defense Evasion",
            "technique": "Impair Defenses"
        },
        "name": "System Audit Policy Was Altered",
        "recommendation": "Investigate possible log tampering.",
        "severity": "High"
    },
    "4720": {
        "cat": "Account Management",
        "description": "A new local user account was created.",
        "detection": "User Account Created",
        "mitre": {
            "id": "T1136",
            "tactic": "Persistence",
            "technique": "Create Account"
        },
        "name": "A Local User Account Was Created",
        "recommendation": "Verify creator, privileges and business justification.",
        "severity": "High"
    },
    "4722": {
        "cat": "Account Management",
        "description": "Previously disabled account enabled.",
        "detection": "User Account Enabled",
        "mitre": {
            "id": "T1078",
            "tactic": "Defense Evasion",
            "technique": "Valid Accounts"
        },
        "name": "A User Account Was Enabled",
        "recommendation": "Confirm account reactivation.",
        "severity": "Medium"
    },
    "4723": {
        "cat": "Account Management",
        "description": "Password change attempted.",
        "detection": "Password Change Attempt",
        "mitre": {
            "id": "T1098",
            "tactic": "Persistence",
            "technique": "Account Manipulation"
        },
        "name": "An Attempt Was Made to Change an Account Password",
        "recommendation": "Validate user activity.",
        "severity": "Medium"
    },
    "4724": {
        "cat": "Account Management",
        "description": "Password reset performed.",
        "detection": "Password Reset",
        "mitre": {
            "id": "T1098",
            "tactic": "Persistence",
            "technique": "Account Manipulation"
        },
        "name": "An Attempt Was Made to Reset an Account Password",
        "recommendation": "Verify administrator activity.",
        "severity": "High"
    },
    "4725": {
        "cat": "Account Management",
        "description": "User account disabled.",
        "detection": "User Account Disabled",
        "mitre": {
            "id": "N/A",
            "tactic": "N/A",
            "technique": "Account Disabled"
        },
        "name": "A User Account Was Disabled",
        "recommendation": "Expected administrative activity.",
        "severity": "Low"
    },
    "4726": {
        "cat": "Account Management",
        "description": "User account removed.",
        "detection": "User Account Deleted",
        "mitre": {
            "id": "T1531",
            "tactic": "Impact",
            "technique": "Account Access Removal"
        },
        "name": "A User Account Was Deleted",
        "recommendation": "Verify deletion request.",
        "severity": "Medium"
    },
    "4727": {
        "cat": "Account Management",
        "description": "A Security-Enabled Global Group Was Created.",
        "detection": "A Security-Enabled Global Group Was Created",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "A Security-Enabled Global Group Was Created",
        "recommendation": "Review the event manually.",
        "severity": "Medium"
    },
    "4728": {
        "cat": "Account Management",
        "description": "User added to privileged group.",
        "detection": "User Added To Security Group",
        "mitre": {
            "id": "T1098",
            "tactic": "Persistence",
            "technique": "Account Manipulation"
        },
        "name": "Member Added to Security-Enabled Global Group",
        "recommendation": "Review group membership.",
        "severity": "High"
    },
    "4729": {
        "cat": "General Audit",
        "description": "User removed from security group.",
        "detection": "User Removed From Security Group",
        "mitre": {
            "id": "N/A",
            "tactic": "N/A",
            "technique": "Group Membership Changed"
        },
        "name": "User Removed From Security Group",
        "recommendation": "Confirm administrative request.",
        "severity": "Low"
    },
    "4730": {
        "cat": "Account Management",
        "description": "A Security-Enabled Global Group Was Deleted.",
        "detection": "A Security-Enabled Global Group Was Deleted",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "A Security-Enabled Global Group Was Deleted",
        "recommendation": "Review the event manually.",
        "severity": "Medium"
    },
    "4731": {
        "cat": "Account Management",
        "description": "A Security-Enabled Local Group Was Created.",
        "detection": "A Security-Enabled Local Group Was Created",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "A Security-Enabled Local Group Was Created",
        "recommendation": "Review the event manually.",
        "severity": "Medium"
    },
    "4732": {
        "cat": "Account Management",
        "description": "Account added to local group.",
        "detection": "Local Group Membership Added",
        "mitre": {
            "id": "T1098",
            "tactic": "Persistence",
            "technique": "Account Manipulation"
        },
        "name": "Member Added to Security-Enabled Local Group",
        "recommendation": "Review privilege escalation.",
        "severity": "High"
    },
    "4733": {
        "cat": "Account Management",
        "description": "Account removed from local group.",
        "detection": "Local Group Membership Removed",
        "mitre": {
            "id": "N/A",
            "tactic": "N/A",
            "technique": "Group Membership Removed"
        },
        "name": "A Member Was Removed From a Local Group",
        "recommendation": "Expected administrative activity.",
        "severity": "Low"
    },
    "4734": {
        "cat": "Account Management",
        "description": "A Security-Enabled Local Group Was Deleted.",
        "detection": "A Security-Enabled Local Group Was Deleted",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "A Security-Enabled Local Group Was Deleted",
        "recommendation": "Review the event manually.",
        "severity": "Medium"
    },
    "4735": {
        "cat": "General Audit",
        "description": "Security group modified.",
        "detection": "Security Group Changed",
        "mitre": {
            "id": "T1098",
            "tactic": "Persistence",
            "technique": "Account Manipulation"
        },
        "name": "Security Group Changed",
        "recommendation": "Review changes.",
        "severity": "Medium"
    },
    "4737": {
        "cat": "Account Management",
        "description": "A Security-Enabled Global Group Was Changed.",
        "detection": "A Security-Enabled Global Group Was Changed",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "A Security-Enabled Global Group Was Changed",
        "recommendation": "Review the event manually.",
        "severity": "Low"
    },
    "4738": {
        "cat": "Account Management",
        "description": "User account properties changed.",
        "detection": "User Account Modified",
        "mitre": {
            "id": "T1098",
            "tactic": "Persistence",
            "technique": "Account Manipulation"
        },
        "name": "A User Account Detail Was Changed",
        "recommendation": "Review modifications.",
        "severity": "Medium"
    },
    "4740": {
        "cat": "General Audit",
        "description": "User account locked.",
        "detection": "Account Locked Out",
        "mitre": {
            "id": "T1110",
            "tactic": "Credential Access",
            "technique": "Brute Force"
        },
        "name": "Account Locked Out",
        "recommendation": "Investigate repeated failed logins.",
        "severity": "Medium"
    },
    "4754": {
        "cat": "Account Management",
        "description": "A Security-Enabled Universal Group Was Created.",
        "detection": "A Security-Enabled Universal Group Was Created",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "A Security-Enabled Universal Group Was Created",
        "recommendation": "Review the event manually.",
        "severity": "Medium"
    },
    "4755": {
        "cat": "Account Management",
        "description": "A Security-Enabled Universal Group Was Changed.",
        "detection": "A Security-Enabled Universal Group Was Changed",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "A Security-Enabled Universal Group Was Changed",
        "recommendation": "Review the event manually.",
        "severity": "Low"
    },
    "4756": {
        "cat": "Account Management",
        "description": "Member Added to Security-Enabled Universal Group.",
        "detection": "Member Added to Security-Enabled Universal Group",
        "mitre": {
            "id": "T1098",
            "tactic": "Persistence",
            "technique": "Account Manipulation"
        },
        "name": "Member Added to Security-Enabled Universal Group",
        "recommendation": "Review the event manually.",
        "severity": "High"
    },
    "4757": {
        "cat": "Account Management",
        "description": "A Member Was Removed From a Universal Group.",
        "detection": "A Member Was Removed From a Universal Group",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "A Member Was Removed From a Universal Group",
        "recommendation": "Review the event manually.",
        "severity": "Medium"
    },
    "4758": {
        "cat": "Account Management",
        "description": "A Security-Enabled Universal Group Was Deleted.",
        "detection": "A Security-Enabled Universal Group Was Deleted",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "A Security-Enabled Universal Group Was Deleted",
        "recommendation": "Review the event manually.",
        "severity": "Medium"
    },
    "4768": {
        "cat": "Kerberos",
        "description": "Kerberos TGT requested.",
        "detection": "Kerberos TGT Request",
        "mitre": {
            "id": "T1558",
            "tactic": "Credential Access",
            "technique": "Steal or Forge Kerberos Tickets"
        },
        "name": "Kerberos Authentication Ticket (TGT) Requested",
        "recommendation": "Monitor for abnormal requests.",
        "severity": "Low"
    },
    "4769": {
        "cat": "Kerberos",
        "description": "Service ticket requested.",
        "detection": "Kerberos Service Ticket",
        "mitre": {
            "id": "T1558",
            "tactic": "Credential Access",
            "technique": "Kerberos Service Ticket"
        },
        "name": "Kerberos Service Ticket (TGS) Requested",
        "recommendation": "Review unusual service usage.",
        "severity": "Low"
    },
    "4771": {
        "cat": "Kerberos",
        "description": "Kerberos pre-authentication failed.",
        "detection": "Kerberos Authentication Failed",
        "mitre": {
            "id": "T1110",
            "tactic": "Credential Access",
            "technique": "Brute Force"
        },
        "name": "Kerberos Pre-Authentication Failed",
        "recommendation": "Investigate authentication failures.",
        "severity": "Medium"
    },
    "4776": {
        "cat": "Authentication",
        "description": "NTLM authentication attempt.",
        "detection": "NTLM Authentication",
        "mitre": {
            "id": "T1550",
            "tactic": "Defense Evasion",
            "technique": "Use Alternate Authentication Material"
        },
        "name": "Domain Controller Attempted to Validate Credentials",
        "recommendation": "Review authentication source.",
        "severity": "Low"
    },
    "4778": {
        "cat": "Remote Desktop",
        "description": "An RDP Session Was Reconnected.",
        "detection": "An RDP Session Was Reconnected",
        "mitre": {
            "id": "T1021.001",
            "tactic": "Lateral Movement",
            "technique": "Remote Services: Remote Desktop Services"
        },
        "name": "An RDP Session Was Reconnected",
        "recommendation": "Review the event manually.",
        "severity": "Low"
    },
    "4779": {
        "cat": "Remote Desktop",
        "description": "An RDP Session Was Disconnected.",
        "detection": "An RDP Session Was Disconnected",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "An RDP Session Was Disconnected",
        "recommendation": "Review the event manually.",
        "severity": "Informational"
    },
    "4781": {
        "cat": "Account Management",
        "description": "The Name of an Account Was Changed.",
        "detection": "The Name of an Account Was Changed",
        "mitre": {
            "id": "T1098",
            "tactic": "Persistence",
            "technique": "Account Manipulation"
        },
        "name": "The Name of an Account Was Changed",
        "recommendation": "Review the event manually.",
        "severity": "Medium"
    },
    "4794": {
        "cat": "Policy Changes",
        "description": "An Attempt to Set Directory Services Password Enforcement.",
        "detection": "An Attempt to Set Directory Services Password Enforcement",
        "mitre": {
            "id": "T1201",
            "tactic": "Unknown",
            "technique": "T1201"
        },
        "name": "An Attempt to Set Directory Services Password Enforcement",
        "recommendation": "Review the event manually.",
        "severity": "High"
    },
    "4798": {
        "cat": "Discovery",
        "description": "Local Group Membership Enumeration.",
        "detection": "Local Group Membership Enumeration",
        "mitre": {
            "id": "T1087",
            "tactic": "Discovery",
            "technique": "Account Discovery"
        },
        "name": "Local Group Membership Enumeration",
        "recommendation": "Review the event manually.",
        "severity": "Medium"
    },
    "4817": {
        "cat": "Policy Changes",
        "description": "Audit Policy on an Object Was Changed.",
        "detection": "Audit Policy on an Object Was Changed",
        "mitre": {
            "id": "T1562.001",
            "tactic": "Defense Evasion",
            "technique": "Disable or Modify Tools"
        },
        "name": "Audit Policy on an Object Was Changed",
        "recommendation": "Review the event manually.",
        "severity": "Medium"
    },
    "4826": {
        "cat": "System Integrity",
        "description": "Data Protection Master Key Was Backed Up.",
        "detection": "Data Protection Master Key Was Backed Up",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "Data Protection Master Key Was Backed Up",
        "recommendation": "Review the event manually.",
        "severity": "Low"
    },
    "4904": {
        "cat": "System Integrity",
        "description": "An Security Event Source Attempted to Register.",
        "detection": "An Security Event Source Attempted to Register",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "An Security Event Source Attempted to Register",
        "recommendation": "Review the event manually.",
        "severity": "Medium"
    },
    "4905": {
        "cat": "System Integrity",
        "description": "An Security Event Source Was Unregistered.",
        "detection": "An Security Event Source Was Unregistered",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "An Security Event Source Was Unregistered",
        "recommendation": "Review the event manually.",
        "severity": "High"
    },
    "4952": {
        "cat": "Firewall Activity",
        "description": "A Local Firewall Rule Extension Was Changed.",
        "detection": "A Local Firewall Rule Extension Was Changed",
        "mitre": {
            "id": "T1562.004",
            "tactic": "Defense Evasion",
            "technique": "Impair Defenses: Disable or Modify System Firewall"
        },
        "name": "A Local Firewall Rule Extension Was Changed",
        "recommendation": "Review the event manually.",
        "severity": "Medium"
    },
    "4964": {
        "cat": "Privilege Escalation",
        "description": "Special Groups Mapped Over Dynamic Logon Token.",
        "detection": "Special Groups Mapped Over Dynamic Logon Token",
        "mitre": {
            "id": "T1078",
            "tactic": "Defense Evasion / Persistence",
            "technique": "Valid Accounts"
        },
        "name": "Special Groups Mapped Over Dynamic Logon Token",
        "recommendation": "Review the event manually.",
        "severity": "Medium"
    },
    "500": {
        "cat": "PowerShell",
        "description": "PowerShell Pipeline Operational Modification.",
        "detection": "PowerShell Pipeline Operational Modification",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "PowerShell Pipeline Operational Modification",
        "recommendation": "Review the event manually.",
        "severity": "Low"
    },
    "5001": {
        "cat": "Antivirus",
        "description": "Windows Defender: Real-Time Monitoring Disabled Bypass.",
        "detection": "Windows Defender: Real-Time Monitoring Disabled Bypass",
        "mitre": {
            "id": "T1562.001",
            "tactic": "Defense Evasion",
            "technique": "Disable or Modify Tools"
        },
        "name": "Windows Defender: Real-Time Monitoring Disabled Bypass",
        "recommendation": "Review the event manually.",
        "severity": "Critical"
    },
    "5007": {
        "cat": "General Audit",
        "description": "Microsoft Defender configuration modified.",
        "detection": "Windows Defender Configuration Changed",
        "mitre": {
            "id": "T1562.001",
            "tactic": "Defense Evasion",
            "technique": "Disable or Modify Security Tools"
        },
        "name": "Windows Defender Configuration Changed",
        "recommendation": "Verify configuration changes.",
        "severity": "High"
    },
    "5024": {
        "cat": "Firewall Activity",
        "description": "The Windows Firewall Service Has Started Successfully.",
        "detection": "The Windows Firewall Service Has Started Successfully",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "The Windows Firewall Service Has Started Successfully",
        "recommendation": "Review the event manually.",
        "severity": "Informational"
    },
    "5025": {
        "cat": "Firewall Activity",
        "description": "The Windows Firewall Service Has Been Stopped.",
        "detection": "The Windows Firewall Service Has Been Stopped",
        "mitre": {
            "id": "T1562.001",
            "tactic": "Defense Evasion",
            "technique": "Disable or Modify Tools"
        },
        "name": "The Windows Firewall Service Has Been Stopped",
        "recommendation": "Review the event manually.",
        "severity": "Critical"
    },
    "5031": {
        "cat": "Firewall Activity",
        "description": "The Windows Firewall Service Blocked an Inbound Connection.",
        "detection": "The Windows Firewall Service Blocked an Inbound Connection",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "The Windows Firewall Service Blocked an Inbound Connection",
        "recommendation": "Review the event manually.",
        "severity": "Low"
    },
    "5136": {
        "cat": "Active Directory",
        "description": "A Directory Service Object Was Modified.",
        "detection": "A Directory Service Object Was Modified",
        "mitre": {
            "id": "T1484",
            "tactic": "Defense Evasion / Persistence",
            "technique": "Domain Policy Modification"
        },
        "name": "A Directory Service Object Was Modified",
        "recommendation": "Review the event manually.",
        "severity": "High"
    },
    "5140": {
        "cat": "Network Share",
        "description": "A network share was accessed.",
        "detection": "Network Share Access",
        "mitre": {
            "id": "T1021.002",
            "tactic": "Lateral Movement",
            "technique": "SMB/Windows Admin Shares"
        },
        "name": "A Network Share Object Was Accessed",
        "recommendation": "Verify source host and accessed share.",
        "severity": "Low"
    },
    "5141": {
        "cat": "Active Directory",
        "description": "A Directory Service Object Was Deleted.",
        "detection": "A Directory Service Object Was Deleted",
        "mitre": {
            "id": "T1070",
            "tactic": "Unknown",
            "technique": "T1070"
        },
        "name": "A Directory Service Object Was Deleted",
        "recommendation": "Review the event manually.",
        "severity": "High"
    },
    "5142": {
        "cat": "Network Share",
        "description": "A Network Share Object Was Added.",
        "detection": "A Network Share Object Was Added",
        "mitre": {
            "id": "T1021.002",
            "tactic": "Lateral Movement",
            "technique": "Remote Services: SMB/Windows File Sharing"
        },
        "name": "A Network Share Object Was Added",
        "recommendation": "Review the event manually.",
        "severity": "Medium"
    },
    "5145": {
        "cat": "Network Share",
        "description": "Detailed network share access detected.",
        "detection": "Detailed File Share Access",
        "mitre": {
            "id": "T1021.002",
            "tactic": "Lateral Movement",
            "technique": "SMB"
        },
        "name": "Network Share Object Checked For Specific Access",
        "recommendation": "Investigate unusual file access.",
        "severity": "Medium"
    },
    "5156": {
        "cat": "Network Connection",
        "description": "Windows Filtering Platform permitted a connection.",
        "detection": "Network Connection Allowed",
        "mitre": {
            "id": "T1049",
            "tactic": "Discovery",
            "technique": "System Network Connections Discovery"
        },
        "name": "Windows Filtering Platform Allowed a Connection",
        "recommendation": "Monitor unexpected outbound connections.",
        "severity": "Informational"
    },
    "5157": {
        "cat": "Network Connection",
        "description": "Windows Filtering Platform Blocked a Network Connection.",
        "detection": "Windows Filtering Platform Blocked a Network Connection",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "Windows Filtering Platform Blocked a Network Connection",
        "recommendation": "Review the event manually.",
        "severity": "Low"
    },
    "5158": {
        "cat": "General Audit",
        "description": "A process bound to a local TCP/UDP port.",
        "detection": "Port Binding",
        "mitre": {
            "id": "T1571",
            "tactic": "Command and Control",
            "technique": "Non-Standard Port"
        },
        "name": "Port Binding",
        "recommendation": "Investigate uncommon listening ports.",
        "severity": "Medium"
    },
    "5379": {
        "cat": "Credential Access",
        "description": "Credential Manager Vault Read.",
        "detection": "Credential Manager Vault Read",
        "mitre": {
            "id": "T1003",
            "tactic": "Credential Access",
            "technique": "Credential Hunting"
        },
        "name": "Credential Manager Vault Read",
        "recommendation": "Review the event manually.",
        "severity": "Medium"
    },
    "6005": {
        "cat": "System Health",
        "description": "The Event Log Service Was Started (System Boot Init).",
        "detection": "The Event Log Service Was Started (System Boot Init)",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "The Event Log Service Was Started (System Boot Init)",
        "recommendation": "Review the event manually.",
        "severity": "Low"
    },
    "6006": {
        "cat": "System Health",
        "description": "The Event Log Service Was Stopped (System Shutdown).",
        "detection": "The Event Log Service Was Stopped (System Shutdown)",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "The Event Log Service Was Stopped (System Shutdown)",
        "recommendation": "Review the event manually.",
        "severity": "Medium"
    },
    "7": {
        "cat": "General Audit",
        "description": "Module or DLL loaded.",
        "detection": "Sysmon Image Loaded",
        "mitre": {
            "id": "T1574",
            "tactic": "Persistence",
            "technique": "Hijack Execution Flow"
        },
        "name": "Sysmon Image Loaded",
        "recommendation": "Look for unsigned DLLs.",
        "severity": "Low"
    },
    "7040": {
        "cat": "System Health",
        "description": "Windows service startup configuration changed.",
        "detection": "Service Startup Changed",
        "mitre": {
            "id": "T1543.003",
            "tactic": "Persistence",
            "technique": "Windows Service"
        },
        "name": "Service Startup Config Altered (Defenses Impaired)",
        "recommendation": "Review service startup type.",
        "severity": "Medium"
    },
    "7045": {
        "cat": "General Audit",
        "description": "A new Windows service was installed.",
        "detection": "New Windows Service Installed",
        "mitre": {
            "id": "T1543.003",
            "tactic": "Persistence",
            "technique": "Create or Modify System Process"
        },
        "name": "New Windows Service Installed",
        "recommendation": "Validate service binary and publisher.",
        "severity": "Critical"
    },
    "8": {
        "cat": "General Audit",
        "description": "Remote thread creation detected.",
        "detection": "Remote Thread Created",
        "mitre": {
            "id": "T1055",
            "tactic": "Defense Evasion",
            "technique": "Process Injection"
        },
        "name": "Remote Thread Created",
        "recommendation": "Investigate possible code injection.",
        "severity": "High"
    },
    "800": {
        "cat": "PowerShell",
        "description": "PowerShell Pipeline Execution Detail Command.",
        "detection": "PowerShell Pipeline Execution Detail Command",
        "mitre": {
            "id": "T1059.001",
            "tactic": "Execution",
            "technique": "Command and Scripting Interpreter: PowerShell"
        },
        "name": "PowerShell Pipeline Execution Detail Command",
        "recommendation": "Review the event manually.",
        "severity": "Medium"
    },
    "sysmon_1": {
        "cat": "Sysmon Telemetry",
        "description": "Sysmon recorded process creation.",
        "detection": "Sysmon Process Creation",
        "mitre": {
            "id": "T1059",
            "tactic": "Execution",
            "technique": "Command and Scripting Interpreter"
        },
        "name": "Sysmon: Process Creation Trace",
        "recommendation": "Inspect parent process and command line.",
        "severity": "Medium"
    },
    "sysmon_10": {
        "cat": "Sysmon Telemetry",
        "description": "Process accessed another process.",
        "detection": "Process Access",
        "mitre": {
            "id": "T1003",
            "tactic": "Credential Access",
            "technique": "OS Credential Dumping"
        },
        "name": "Sysmon: ProcessAccess Detected (LSASS Injection)",
        "recommendation": "Review for LSASS access.",
        "severity": "High"
    },
    "sysmon_11": {
        "cat": "Sysmon Telemetry",
        "description": "A file was created.",
        "detection": "File Created",
        "mitre": {
            "id": "T1105",
            "tactic": "Command and Control",
            "technique": "Ingress Tool Transfer"
        },
        "name": "Sysmon: FileCreate Detected (Malicious Dropper)",
        "recommendation": "Inspect suspicious file paths.",
        "severity": "Low"
    },
    "sysmon_12": {
        "cat": "Sysmon Telemetry",
        "description": "Sysmon: RegistryEvent (Object Created/Deleted).",
        "detection": "Sysmon: RegistryEvent (Object Created/Deleted)",
        "mitre": {
            "id": "T1112",
            "tactic": "Defense Evasion",
            "technique": "Modify Registry"
        },
        "name": "Sysmon: RegistryEvent (Object Created/Deleted)",
        "recommendation": "Review the event manually.",
        "severity": "Medium"
    },
    "sysmon_13": {
        "cat": "Sysmon Telemetry",
        "description": "Registry value changed.",
        "detection": "Registry Value Modified",
        "mitre": {
            "id": "T1112",
            "tactic": "Defense Evasion",
            "technique": "Modify Registry"
        },
        "name": "Sysmon: RegistryEvent (Value Set)",
        "recommendation": "Review persistence locations.",
        "severity": "Medium"
    },
    "sysmon_14": {
        "cat": "Sysmon Registry",
        "description": "Sysmon: RegistryEvent Object Renamed.",
        "detection": "Sysmon: RegistryEvent Object Renamed",
        "mitre": {
            "id": "T1112",
            "tactic": "Defense Evasion",
            "technique": "Modify Registry"
        },
        "name": "Sysmon: RegistryEvent Object Renamed",
        "recommendation": "Review the event manually.",
        "severity": "Low"
    },
    "sysmon_15": {
        "cat": "Sysmon Telemetry",
        "description": "Sysmon: Alternate Data Stream Detected.",
        "detection": "Sysmon: Alternate Data Stream Detected",
        "mitre": {
            "id": "T1564",
            "tactic": "Unknown",
            "technique": "T1564"
        },
        "name": "Sysmon: Alternate Data Stream Detected",
        "recommendation": "Review the event manually.",
        "severity": "High"
    },
    "sysmon_16": {
        "cat": "Sysmon Diagnostics",
        "description": "Sysmon: Sysmon Configuration Mismatch/Updated.",
        "detection": "Sysmon: Sysmon Configuration Mismatch/Updated",
        "mitre": {
            "id": "T1562.001",
            "tactic": "Defense Evasion",
            "technique": "Disable or Modify Tools"
        },
        "name": "Sysmon: Sysmon Configuration Mismatch/Updated",
        "recommendation": "Review the event manually.",
        "severity": "Medium"
    },
    "sysmon_17": {
        "cat": "Sysmon IPC",
        "description": "Sysmon: PipeEvent Created (Named Pipe Lateral Movement).",
        "detection": "Sysmon: PipeEvent Created (Named Pipe Lateral Movement)",
        "mitre": {
            "id": "T1570",
            "tactic": "Lateral Movement",
            "technique": "Lateral Tool Transfer"
        },
        "name": "Sysmon: PipeEvent Created (Named Pipe Lateral Movement)",
        "recommendation": "Review the event manually.",
        "severity": "Medium"
    },
    "sysmon_18": {
        "cat": "Sysmon IPC",
        "description": "Sysmon: PipeEvent Connected.",
        "detection": "Sysmon: PipeEvent Connected",
        "mitre": {
            "id": "T1570",
            "tactic": "Lateral Movement",
            "technique": "Lateral Tool Transfer"
        },
        "name": "Sysmon: PipeEvent Connected",
        "recommendation": "Review the event manually.",
        "severity": "Low"
    },
    "sysmon_19": {
        "cat": "Sysmon WMI",
        "description": "Sysmon: WmiEvent WmiEventFilter Activity Detected.",
        "detection": "Sysmon: WmiEvent WmiEventFilter Activity Detected",
        "mitre": {
            "id": "T1546.003",
            "tactic": "Unknown",
            "technique": "T1546.003"
        },
        "name": "Sysmon: WmiEvent WmiEventFilter Activity Detected",
        "recommendation": "Review the event manually.",
        "severity": "High"
    },
    "sysmon_2": {
        "cat": "Sysmon Telemetry",
        "description": "Sysmon: A Process Changed a File Creation Time.",
        "detection": "Sysmon: A Process Changed a File Creation Time",
        "mitre": {
            "id": "T1070.006",
            "tactic": "Defense Evasion",
            "technique": "Indicator Removal: Timestomp"
        },
        "name": "Sysmon: A Process Changed a File Creation Time",
        "recommendation": "Review the event manually.",
        "severity": "Medium"
    },
    "sysmon_20": {
        "cat": "Sysmon WMI",
        "description": "Sysmon: WmiEvent WmiEventConsumer Activity.",
        "detection": "Sysmon: WmiEvent WmiEventConsumer Activity",
        "mitre": {
            "id": "T1546.003",
            "tactic": "Unknown",
            "technique": "T1546.003"
        },
        "name": "Sysmon: WmiEvent WmiEventConsumer Activity",
        "recommendation": "Review the event manually.",
        "severity": "High"
    },
    "sysmon_21": {
        "cat": "Sysmon WMI",
        "description": "A WMI event consumer was bound to a filter.",
        "detection": "WMI ConsumerToFilter Binding",
        "mitre": {
            "id": "T1546.003",
            "tactic": "Persistence",
            "technique": "WMI Event Subscription"
        },
        "name": "Sysmon: WmiEvent ConsumerToFilter Binding Activity Detected",
        "recommendation": "Review WMI persistence subscriptions.",
        "severity": "High"
    },
    "sysmon_22": {
        "cat": "Sysmon Telemetry",
        "description": "Sysmon: Operational DNS Query Dispatched.",
        "detection": "Sysmon: Operational DNS Query Dispatched",
        "mitre": {
            "id": "T1071.004",
            "tactic": "Unknown",
            "technique": "T1071.004"
        },
        "name": "Sysmon: Operational DNS Query Dispatched",
        "recommendation": "Review the event manually.",
        "severity": "Low"
    },
    "sysmon_23": {
        "cat": "Sysmon File",
        "description": "Sysmon: FileDelete Restleaved (File Asset Wiped).",
        "detection": "Sysmon: FileDelete Restleaved (File Asset Wiped)",
        "mitre": {
            "id": "T1070.004",
            "tactic": "Defense Evasion",
            "technique": "Indicator Removal: File Deletion"
        },
        "name": "Sysmon: FileDelete Restleaved (File Asset Wiped)",
        "recommendation": "Review the event manually.",
        "severity": "Low"
    },
    "sysmon_24": {
        "cat": "Sysmon Clipboard",
        "description": "Clipboard contents changed.",
        "detection": "Clipboard Changed",
        "mitre": {
            "id": "T1115",
            "tactic": "Collection",
            "technique": "Clipboard Data"
        },
        "name": "Sysmon: Clipboard Changed Tracking Event",
        "recommendation": "Normal activity; monitor if clipboard exfiltration suspected.",
        "severity": "Informational"
    },
    "sysmon_25": {
        "cat": "Defense Evasion",
        "description": "Sysmon: Process Tampering (Process Hollowing).",
        "detection": "Sysmon: Process Tampering (Process Hollowing)",
        "mitre": {
            "id": "T1036",
            "tactic": "Unknown",
            "technique": "T1036"
        },
        "name": "Sysmon: Process Tampering (Process Hollowing)",
        "recommendation": "Review the event manually.",
        "severity": "Critical"
    },
    "sysmon_26": {
        "cat": "Sysmon Telemetry",
        "description": "Sysmon: FileDelete Detected (Anti-Ransomware Ingest).",
        "detection": "Sysmon: FileDelete Detected (Anti-Ransomware Ingest)",
        "mitre": {
            "id": "T1486",
            "tactic": "Impact",
            "technique": "Data Encrypted for Impact (Ransomware Operational Activity)"
        },
        "name": "Sysmon: FileDelete Detected (Anti-Ransomware Ingest)",
        "recommendation": "Review the event manually.",
        "severity": "Medium"
    },
    "sysmon_3": {
        "cat": "Sysmon Telemetry",
        "description": "Network connection established.",
        "detection": "Sysmon Network Connection",
        "mitre": {
            "id": "T1071",
            "tactic": "Command and Control",
            "technique": "Application Layer Protocol"
        },
        "name": "Sysmon: Network Connection Detected",
        "recommendation": "Investigate suspicious remote IPs.",
        "severity": "Medium"
    },
    "sysmon_4": {
        "cat": "Sysmon Diagnostics",
        "description": "Sysmon: Sysmon Service Status Changed.",
        "detection": "Sysmon: Sysmon Service Status Changed",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "Sysmon: Sysmon Service Status Changed",
        "recommendation": "Review the event manually.",
        "severity": "Informational"
    },
    "sysmon_5": {
        "cat": "Sysmon Telemetry",
        "description": "Sysmon: Process Terminated Event.",
        "detection": "Sysmon: Process Terminated Event",
        "mitre": {
            "id": "N/A",
            "tactic": "Unknown",
            "technique": "Unknown"
        },
        "name": "Sysmon: Process Terminated Event",
        "recommendation": "Review the event manually.",
        "severity": "Low"
    },
    "sysmon_6": {
        "cat": "Sysmon Telemetry",
        "description": "Sysmon: Kernel Driver Loaded.",
        "detection": "Sysmon: Kernel Driver Loaded",
        "mitre": {
            "id": "T1547.006",
            "tactic": "Persistence / Privilege Escalation",
            "technique": "Boot or Logon Autostart Execution: Kernel Modules and Drivers"
        },
        "name": "Sysmon: Kernel Driver Loaded",
        "recommendation": "Review the event manually.",
        "severity": "High"
    },
    "sysmon_7": {
        "cat": "Sysmon Telemetry",
        "description": "Module or DLL loaded.",
        "detection": "Sysmon Image Loaded",
        "mitre": {
            "id": "T1574",
            "tactic": "Persistence",
            "technique": "Hijack Execution Flow"
        },
        "name": "Sysmon: DLL Image Loaded (Potential Injection)",
        "recommendation": "Look for unsigned DLLs.",
        "severity": "Low"
    },
    "sysmon_8": {
        "cat": "Sysmon Telemetry",
        "description": "Remote thread creation detected.",
        "detection": "Remote Thread Created",
        "mitre": {
            "id": "T1055",
            "tactic": "Defense Evasion",
            "technique": "Process Injection"
        },
        "name": "Sysmon: CreateRemoteThread Detected (Code Injection)",
        "recommendation": "Investigate possible code injection.",
        "severity": "High"
    },
    "sysmon_9": {
        "cat": "Sysmon Telemetry",
        "description": "Sysmon: RawAccessRead Detected.",
        "detection": "Sysmon: RawAccessRead Detected",
        "mitre": {
            "id": "T1003.006",
            "tactic": "Credential Access",
            "technique": "OS Credential Dumping: DCC2/Cached Domain Credentials"
        },
        "name": "Sysmon: RawAccessRead Detected",
        "recommendation": "Review the event manually.",
        "severity": "High"
    }
}

# ============================================================================
# SUSPICIOUS PROCESS INTELLIGENCE
# ============================================================================
PROCESS_RULES = {
    "bcdedit.exe": {
        "description": "Boot configuration changed.",
        "detection": "Boot Configuration Modified",
        "mitre": {
            "id": "T1562",
            "tactic": "Defense Evasion",
            "technique": "Impair Defenses"
        },
        "recommendation": "Verify modification.",
        "severity": "Critical"
    },
    "bitsadmin.exe": {
        "description": "BITSAdmin executed.",
        "detection": "BITSAdmin Execution",
        "mitre": {
            "id": "T1197",
            "tactic": "Persistence",
            "technique": "BITS Jobs"
        },
        "recommendation": "Check scheduled transfers.",
        "severity": "High"
    },
    "certutil.exe": {
        "description": "CertUtil may download or decode payloads.",
        "detection": "CertUtil Abuse",
        "mitre": {
            "id": "T1105",
            "tactic": "Command and Control",
            "technique": "Ingress Tool Transfer"
        },
        "recommendation": "Investigate downloaded files.",
        "severity": "Critical"
    },
    "cmd.exe": {
        "description": "Windows command shell launched.",
        "detection": "Windows Command Shell",
        "mitre": {
            "id": "T1059.003",
            "tactic": "Execution",
            "technique": "Windows Command Shell"
        },
        "recommendation": "Inspect executed commands.",
        "severity": "Medium"
    },
    "diskshadow.exe": {
        "description": "DiskShadow executed.",
        "detection": "DiskShadow Execution",
        "mitre": {
            "id": "T1003",
            "tactic": "Credential Access",
            "technique": "OS Credential Dumping"
        },
        "recommendation": "Review snapshot creation.",
        "severity": "Critical"
    },
    "mimikatz.exe": {
        "description": "Known credential dumping tool.",
        "detection": "Mimikatz Detected",
        "mitre": {
            "id": "T1003",
            "tactic": "Credential Access",
            "technique": "Credential Dumping"
        },
        "recommendation": "Immediately isolate host.",
        "severity": "Critical"
    },
    "mshta.exe": {
        "description": "MSHTA launched.",
        "detection": "MSHTA Execution",
        "mitre": {
            "id": "T1218.005",
            "tactic": "Defense Evasion",
            "technique": "Mshta"
        },
        "recommendation": "Inspect remote URLs.",
        "severity": "Critical"
    },
    "net.exe": {
        "description": "net.exe executed.",
        "detection": "Network Command",
        "mitre": {
            "id": "T1087",
            "tactic": "Discovery",
            "technique": "Account Discovery"
        },
        "recommendation": "Inspect account enumeration.",
        "severity": "Medium"
    },
    "net1.exe": {
        "description": "net1.exe executed.",
        "detection": "Network Command",
        "mitre": {
            "id": "T1087",
            "tactic": "Discovery",
            "technique": "Account Discovery"
        },
        "recommendation": "Inspect account enumeration.",
        "severity": "Medium"
    },
    "nltest.exe": {
        "description": "NLTEST executed.",
        "detection": "Domain Discovery",
        "mitre": {
            "id": "T1018",
            "tactic": "Discovery",
            "technique": "Remote System Discovery"
        },
        "recommendation": "Inspect domain enumeration.",
        "severity": "Medium"
    },
    "powershell.exe": {
        "description": "PowerShell executed.",
        "detection": "PowerShell Execution",
        "mitre": {
            "id": "T1059.001",
            "tactic": "Execution",
            "technique": "PowerShell"
        },
        "recommendation": "Inspect command line for EncodedCommand, DownloadString, IEX.",
        "severity": "High"
    },
    "procdump.exe": {
        "description": "ProcDump executed.",
        "detection": "Credential Dump Attempt",
        "mitre": {
            "id": "T1003.001",
            "tactic": "Credential Access",
            "technique": "LSASS Memory"
        },
        "recommendation": "Investigate LSASS dump.",
        "severity": "Critical"
    },
    "psexec.exe": {
        "description": "PsExec executed.",
        "detection": "PsExec Execution",
        "mitre": {
            "id": "T1021.002",
            "tactic": "Lateral Movement",
            "technique": "SMB"
        },
        "recommendation": "Investigate remote execution.",
        "severity": "Critical"
    },
    "pwsh.exe": {
        "description": "PowerShell Core executed.",
        "detection": "PowerShell Core",
        "mitre": {
            "id": "T1059.001",
            "tactic": "Execution",
            "technique": "PowerShell"
        },
        "recommendation": "Review executed commands.",
        "severity": "High"
    },
    "regsvr32.exe": {
        "description": "Regsvr32 executed.",
        "detection": "Regsvr32 Execution",
        "mitre": {
            "id": "T1218.010",
            "tactic": "Defense Evasion",
            "technique": "Regsvr32"
        },
        "recommendation": "Look for Squiblydoo behavior.",
        "severity": "High"
    },
    "rundll32.exe": {
        "description": "RunDLL32 executed.",
        "detection": "RunDLL32 Execution",
        "mitre": {
            "id": "T1218.011",
            "tactic": "Defense Evasion",
            "technique": "RunDLL32"
        },
        "recommendation": "Validate DLL path.",
        "severity": "High"
    },
    "sc.exe": {
        "description": "Service Control Manager command.",
        "detection": "Service Control",
        "mitre": {
            "id": "T1543.003",
            "tactic": "Persistence",
            "technique": "Windows Service"
        },
        "recommendation": "Review service changes.",
        "severity": "Medium"
    },
    "schtasks.exe": {
        "description": "schtasks executed.",
        "detection": "Scheduled Task Command",
        "mitre": {
            "id": "T1053.005",
            "tactic": "Persistence",
            "technique": "Scheduled Task"
        },
        "recommendation": "Inspect created tasks.",
        "severity": "High"
    },
    "vssadmin.exe": {
        "description": "Shadow copies manipulated.",
        "detection": "Shadow Copy Deletion",
        "mitre": {
            "id": "T1490",
            "tactic": "Impact",
            "technique": "Inhibit System Recovery"
        },
        "recommendation": "Possible ransomware.",
        "severity": "Critical"
    },
    "whoami.exe": {
        "description": "whoami executed.",
        "detection": "Identity Discovery",
        "mitre": {
            "id": "T1033",
            "tactic": "Discovery",
            "technique": "System Owner Discovery"
        },
        "recommendation": "Review user context.",
        "severity": "Low"
    },
    "wmic.exe": {
        "description": "WMIC executed.",
        "detection": "WMIC Execution",
        "mitre": {
            "id": "T1047",
            "tactic": "Execution",
            "technique": "Windows Management Instrumentation"
        },
        "recommendation": "Review WMI queries.",
        "severity": "High"
    }
}

# ============================================================================
# MITRE ATT&CK GLOSSARY (technique/tactic resolution)
# ============================================================================
MITRE_MATRIX_GLOSSARY = {
    "T1003": {
        "tactic": "Credential Access",
        "technique": "Credential Hunting"
    },
    "T1003.001": {
        "tactic": "Credential Access",
        "technique": "OS Credential Dumping: LSASS Memory"
    },
    "T1003.006": {
        "tactic": "Credential Access",
        "technique": "OS Credential Dumping: DCC2/Cached Domain Credentials"
    },
    "T1021.001": {
        "tactic": "Lateral Movement",
        "technique": "Remote Services: Remote Desktop Services"
    },
    "T1021.002": {
        "tactic": "Lateral Movement",
        "technique": "Remote Services: SMB/Windows File Sharing"
    },
    "T1053.005": {
        "tactic": "Persistence",
        "technique": "Scheduled Task/Job: Scheduled Task"
    },
    "T1055": {
        "tactic": "Privilege Escalation / Defense Evasion",
        "technique": "Process Injection"
    },
    "T1055.012": {
        "tactic": "Privilege Escalation / Defense Evasion",
        "technique": "Process Injection: Process Hollowing"
    },
    "T1059": {
        "tactic": "Execution",
        "technique": "Command and Scripting Interpreter"
    },
    "T1059.001": {
        "tactic": "Execution",
        "technique": "Command and Scripting Interpreter: PowerShell"
    },
    "T1059.003": {
        "tactic": "Execution",
        "technique": "Command and Scripting Interpreter: Windows Command Shell"
    },
    "T1068": {
        "tactic": "Privilege Escalation",
        "technique": "Exploitation for Privilege Escalation"
    },
    "T1070.001": {
        "tactic": "Defense Evasion",
        "technique": "Clear Windows Event Logs"
    },
    "T1070.004": {
        "tactic": "Defense Evasion",
        "technique": "Indicator Removal: File Deletion"
    },
    "T1070.006": {
        "tactic": "Defense Evasion",
        "technique": "Indicator Removal: Timestomp"
    },
    "T1078": {
        "tactic": "Defense Evasion / Persistence",
        "technique": "Valid Accounts"
    },
    "T1078.002": {
        "tactic": "Defense Evasion / Persistence",
        "technique": "Valid Accounts: Domain Accounts"
    },
    "T1087": {
        "tactic": "Discovery",
        "technique": "Account Discovery"
    },
    "T1098": {
        "tactic": "Persistence",
        "technique": "Account Manipulation"
    },
    "T1105": {
        "tactic": "Command and Control",
        "technique": "Ingress Tool Transfer (Malicious Dropper File)"
    },
    "T1110": {
        "tactic": "Credential Access",
        "technique": "Brute Force"
    },
    "T1110.003": {
        "tactic": "Credential Access",
        "technique": "Brute Force: Password Spraying"
    },
    "T1112": {
        "tactic": "Defense Evasion",
        "technique": "Modify Registry"
    },
    "T1115": {
        "tactic": "Collection",
        "technique": "Clipboard Data Collection"
    },
    "T1136.001": {
        "tactic": "Persistence",
        "technique": "Local Account Creation"
    },
    "T1204": {
        "tactic": "Execution",
        "technique": "User Execution (Malicious Attachment Click)"
    },
    "T1484": {
        "tactic": "Defense Evasion / Persistence",
        "technique": "Domain Policy Modification"
    },
    "T1486": {
        "tactic": "Impact",
        "technique": "Data Encrypted for Impact (Ransomware Operational Activity)"
    },
    "T1543.003": {
        "tactic": "Persistence / Privilege Escalation",
        "technique": "Windows Service Creation"
    },
    "T1547.006": {
        "tactic": "Persistence / Privilege Escalation",
        "technique": "Boot or Logon Autostart Execution: Kernel Modules and Drivers"
    },
    "T1558": {
        "tactic": "Credential Access",
        "technique": "Steal or Forge Kerberos Tickets"
    },
    "T1558.003": {
        "tactic": "Credential Access",
        "technique": "Steal or Forge Kerberos Tickets: Kerberoasting"
    },
    "T1562.001": {
        "tactic": "Defense Evasion",
        "technique": "Disable or Modify Tools"
    },
    "T1562.004": {
        "tactic": "Defense Evasion",
        "technique": "Impair Defenses: Disable or Modify System Firewall"
    },
    "T1570": {
        "tactic": "Lateral Movement",
        "technique": "Lateral Tool Transfer"
    },
    "T1574.002": {
        "tactic": "Persistence / Privilege Escalation / Defense Evasion",
        "technique": "Hijack Execution Flow: DLL Side-Loading"
    }
}

# ============================================================================
# UNMAPPED EVENT DEFAULT
# ----------------------------------------------------------------------------
# Explicitly justified by the registry: telemetry whose Event ID has no entry
# here is baseline noise and is classified Informational (not silently upgraded
# from "Unknown" — the registry itself defines the default).
# ============================================================================
DEFAULT_EVENT_RULE = {
    "name": "Windows Event ID {id}",
    "cat": "General Audit",
    "detection": "No Detection Matched",
    "severity": "Informational",
    "mitre": {"id": "N/A", "technique": "Unknown", "tactic": "Unknown"},
    "description": "Unknown Windows Event",
    "recommendation": "Review the event manually or expand Windows Event Rules.",
}

# Legacy default descriptions that predate the explicit "Unknown Windows Event"
# label — normalized to the canonical label at read time so historical rows and
# new rows display identically.
_LEGACY_DEFAULT_DESCRIPTIONS = {
    "no enterprise detection rule matched this windows event.",
    "no detection rule matched this windows event.",
    "no detection matched.",
}


def _rule_for(event_id):
    """Internal lookup: returns the rule dict or the registry default.

    The detection engine defines Sysmon events under bare numeric keys
    (1, 3, 7, 8, 10, 11, 13) while display registries use 'sysmon_N'. The
    sysmon_N entries for those IDs are aligned to the rules' authoritative
    values at module build time, so '7' and 'sysmon_7' resolve identically no
    matter which API path performs the lookup — while genuinely different
    events (e.g. Terminal Services '21' vs Sysmon 'sysmon_21') stay distinct.
    """
    key = str(event_id or "").strip()
    if not key:
        return dict(DEFAULT_EVENT_RULE)
    rule = WINDOWS_EVENT_RULES.get(key)
    if rule is not None:
        return rule
    sysmon_key = f"sysmon_{key}"
    rule = WINDOWS_EVENT_RULES.get(sysmon_key)
    if rule is not None:
        return rule
    if key.startswith("sysmon_"):
        rule = WINDOWS_EVENT_RULES.get(key[7:])
        if rule is not None:
            return rule
    return dict(DEFAULT_EVENT_RULE)


def get_event_rule(event_id):
    """Authoritative Event ID rule: {name, cat, detection, severity, mitre,
    description, recommendation}. Always returns a rule (registry default for
    unmapped IDs) — never None, so every consumer sees identical values."""
    rule = _rule_for(event_id)
    rule = dict(rule)
    if rule.get("name") == "Windows Event ID {id}":
        rule["name"] = rule["name"].format(id=str(event_id or "").replace("sysmon_", ""))
    return rule


def get_process_rule(process_name):
    """Authoritative process rule (basename lookup), or None."""
    if not process_name:
        return None
    process = process_name.lower().split("\\")[-1]
    rule = PROCESS_RULES.get(process)
    if rule is None:
        # allow 'powershell.exe' / 'POWERSHELL.EXE' style mismatches
        rule = PROCESS_RULES.get(process_name)
    return rule


def supported_event_ids():
    return sorted({str(k).replace("sysmon_", "") for k in WINDOWS_EVENT_RULES})


def supported_processes():
    return sorted(PROCESS_RULES.keys())


def resolve_mitre(mitre_id):
    """Resolve a MITRE id to {technique, tactic} via the glossary."""
    if not mitre_id or mitre_id in ("N/A", "Unknown"):
        return {"id": mitre_id or "N/A", "technique": "Unknown", "tactic": "Unknown"}
    entry = MITRE_MATRIX_GLOSSARY.get(mitre_id)
    if entry:
        return {"id": mitre_id, "technique": entry.get("technique", mitre_id),
                "tactic": entry.get("tactic", "Unknown")}
    return {"id": mitre_id, "technique": mitre_id, "tactic": "Unknown"}


# ============================================================================
# DISPLAY ENRICHMENT (single source for every read path)
# ----------------------------------------------------------------------------
# Previously duplicated inside app/routes/logs.py; now lives with the registry
# so the /logs, /timeline, /enterprise and /alerts paths all resolve identical
# detection / severity / MITRE values for the same Event ID.
# ============================================================================

SEVERITY_COUNT_KEYS = ["Critical", "High", "Medium", "Low", "Informational"]


def _normalize_severity_value(raw):
    """Map any stored severity representation to a canonical display level.

    Empty / Unknown / None map to Informational so displayed severities stay
    consistent with SQL-side counting and the dashboard analytics. This is the
    registry's explicit justification for the Informational default above.
    """
    s = str(raw or "").strip()
    if not s or s.lower() in ("unknown", "none", "null", "info", "informational"):
        return "Informational"
    cap = s.capitalize()
    return cap if cap in SEVERITY_COUNT_KEYS else "Informational"


# Enterprise metadata suffixes some event sources append to a process token,
# e.g. 'app.exe, version: 1.2.3, time stamp: 0x6a3570a5' (Task 27). The Process
# field must contain the actual process name, so everything from the first
# ', version:' / ', time stamp:' / ', timestamp:' marker is stripped.
_PROCESS_SUFFIX_RE = re.compile(r",\s*(version|time\s*stamp|timestamp)\s*:")


def _clean_process_token(value):
    """Strip trailing enterprise metadata from one process token."""
    if not value:
        return value
    cleaned = _PROCESS_SUFFIX_RE.split(value.strip(), maxsplit=1)[0]
    return cleaned.strip().rstrip(",").strip()


def sanitize_process_name(image_path, fallback_name):
    """Win32 executable-image extraction: basename of the image path, with
    explicit enterprise tags for missing markers (never 'N/A' leak) and any
    ', version:' / ', time stamp:' suffixes stripped (Task 27).

    When the event genuinely contains no process information (no image, no
    process name), the explicit PROCESS_NOT_AVAILABLE sentinel is returned —
    never a fabricated placeholder like '[System Process]'.
    """
    img_clean = image_path.strip() if image_path else ""
    fallback_clean = _clean_process_token(fallback_name)

    def _empty(value):
        return not value or str(value).strip().lower() in {"-", "none", "null", "n/a", "(null)"}

    if _empty(img_clean):
        if _empty(fallback_clean):
            return PROCESS_NOT_AVAILABLE
        return fallback_clean

    base_name = _clean_process_token(img_clean.replace("\\", "/").split("/")[-1])
    if _empty(base_name):
        return fallback_clean if not _empty(fallback_clean) else PROCESS_NOT_AVAILABLE
    return base_name


def normalize_process_id(raw):
    """Canonical PID display value: the real PID when present, else the
    explicit PID_NOT_AVAILABLE sentinel — never '-' or ''."""
    value = str(raw or "").strip()
    if not value or value.lower() in {"-", "none", "null", "n/a", "(null)"} or value == "0":
        return PID_NOT_AVAILABLE
    return value


def build_mitre_block(mitre_id, detection_name="", severity=""):
    """Canonical MITRE ATT&CK result for one event.

    Returns the enriched block every read path consumes:
      If a single mitre_id is provided, returns a single block:
      {id, name, technique, tactic, confidence, reason}
      
      If a list of mitre_ids is provided, returns a list of blocks:
      [
          {id, name, technique, tactic, confidence, reason},
          ...
      ]

    - id: technique/sub-technique id (e.g. 'T1059.001') or MITRE_UNMAPPED when
      the event evidence supports no mapping — a technique is NEVER assigned
      merely because an Event ID resembles one.
    - name: short technique name (sub-technique when applicable), derived from
      the glossary ('Command and Scripting Interpreter: PowerShell' ->
      'PowerShell').
    - confidence: how strongly the detection evidence supports the mapping
      (severity-based, 0.0 when unmapped).
    - reason: the actual detection rule that produced the mapping.
    """
    # Handle multiple MITRE ids
    if isinstance(mitre_id, list):
        results = []
        for mid in mitre_id:
            block = build_mitre_block(mid, detection_name, severity)
            results.append(block)
        return results
    
    # Handle single MITRE id (original logic)
    raw_id = str(mitre_id or "").strip()
    if not raw_id or raw_id.lower() in {"n/a", "unknown", "none", "null", "-"}:
        return {
            "id": MITRE_UNMAPPED,
            "name": MITRE_UNMAPPED,
            "technique": "No applicable MITRE ATT&CK technique",
            "tactic": "Unknown",
            "confidence": 0.0,
            "reason": "No detection evidence maps this event to a MITRE ATT&CK technique.",
        }

    resolved = resolve_mitre(raw_id)
    technique = resolved.get("technique") or raw_id
    tactic = resolved.get("tactic") or "Unknown"

    name = technique
    if ": " in technique:
        name = technique.rsplit(": ", 1)[-1].strip()

    severity_key = str(severity or "").strip().capitalize()
    confidence = {
        "Critical": 0.95, "High": 0.9, "Medium": 0.8,
        "Low": 0.7, "Informational": 0.5,
    }.get(severity_key, 0.5)

    reason = str(detection_name or "").strip()
    if not reason:
        reason = f"Mapped by Event ID {raw_id}"

    return {
        "id": raw_id,
        "name": name,
        "technique": technique,
        "tactic": tactic,
        "confidence": confidence,
        "reason": reason,
    }


def normalize_event_description(raw):
    """Canonical event description: real description when present, else the
    explicit 'Unknown Windows Event' label for unmapped events."""
    value = str(raw or "").strip()
    if not value or value.lower() in _LEGACY_DEFAULT_DESCRIPTIONS:
        return DEFAULT_EVENT_RULE["description"]
    return value


def is_sysmon_event(event_block):
    """True ONLY when the event actually came from the Sysmon provider.

    Sysmon is determined from the real channel / source / provider fields
    (e.g. channel "Microsoft-Windows-Sysmon/Operational", source "Sysmon"),
    NEVER from the numeric Event ID alone — a Windows event that happens to
    share a number with a Sysmon event (e.g. Security 1 vs Sysmon 1) must not
    be classified as Sysmon. This is the single shared classifier used by
    Alerts and Timeline so the same event classifies identically end-to-end.
    """
    block = event_block or {}
    haystack = " ".join([
        str(block.get("channel", "") or ""),
        str(block.get("source", "") or ""),
        str(block.get("provider", "") or ""),
    ]).lower()
    return "sysmon" in haystack


def resolve_event_lookup_id(event_block):
    """Registry lookup key ('sysmon_N' or 'N') for one event block.

    The single shared classification for every read path (Alerts, Timeline,
    Dashboard): Sysmon events resolve to their sysmon_<N> registry entry,
    everything else to the bare numeric id. Classification never depends on the
    numeric Event ID — only on the actual channel/source/provider.
    """
    raw_id = str((event_block or {}).get("event_id", "") or "")
    if is_sysmon_event(event_block):
        return f"sysmon_{raw_id}"
    return raw_id


def enrich_log_payload(event_id, current_severity="", command_line=""):
    """Resolve detection / severity / MITRE for one Event ID.

    Uses ONLY the authoritative registry. A non-default stored severity (e.g.
    from a process rule like powershell.exe -> High) is preserved; otherwise the
    Event ID's registry severity applies, so every API path shows the same
    severity for the same event.
    """
    id_str = str(event_id or "")
    cmd_lower = command_line.lower() if command_line else ""

    rule = get_event_rule(id_str)

    resolved_severity = rule["severity"]
    mitre_id = rule["mitre"]["id"]

    # Command-line intelligence for process-creation events (kept behavior).
    if id_str in ["4688", "1", "4104"]:
        if "mimikatz" in cmd_lower or "lsass" in cmd_lower or "dump" in cmd_lower:
            mitre_id = "T1003.001"
            resolved_severity = "Critical"
        elif "powershell" in cmd_lower and ("-enc" in cmd_lower or "bypass" in cmd_lower):
            resolved_severity = "High"
            mitre_id = "T1059.001"

    if current_severity and str(current_severity).strip().lower() not in ["info", "informational", "", "none", "unknown"]:
        resolved_severity = current_severity

    mitre_details = resolve_mitre(mitre_id)

    # Full enriched MITRE block (id/name/technique/tactic/confidence/reason,
    # "Unmapped" for events with no applicable mapping) — the single shape
    # every consumer renders.
    mitre_block = build_mitre_block(
        mitre_id, rule["detection"], resolved_severity
    )

    return {
        "detection": rule["detection"],
        "severity": resolved_severity,
        "mitre_id": mitre_id,
        "technique": mitre_details["technique"],
        "tactic": mitre_details["tactic"],
        "mitre": mitre_block,
    }